service: package-anonymous-auth-provider
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
functions:
  authenticateAnonymousUser:
    handler: functions/authenticateAnonymousUser.lambda
    events:
      - http:
          path: anonymous-auth-provider/authenticateAnonymousUser
          method: post